name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  repo-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Tween Wrapper
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          template: repository
          user: __metamethods
          repo: TweenWrapper
          filename: tween-wrapper-metrics.svg
          committer_message: 'feat: Update Repo TweenWrapper [skip ci]'
          plugin_introduction: yes
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_details: lines, bytes-size, percentage
          plugin_languages_limit: 4
          plugin_languages_analysis_timeout: 15
          plugin_people: yes
          plugin_people_types: contributors, stargazers, watchers, sponsors
  user-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Los_Angeles
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_limit: 5
          plugin_activity_load: 300
          plugin_activity_visibility: public
          plugin_followup: yes
          plugin_followup_indepth: yes
          plugin_followup_sections: user
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 20
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 365
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_languages_details: bytes-size, percentage
          plugin_lines: yes
          plugin_habits_facts: yes
          plugin_licenses: yes
          plugin_licenses_setup: bash -c '[[ -f package.json ]] && npm ci || true'
          plugin_licenses_legal: yes
          plugin_licenses_ratio: yes
          plugin_repositories: yes
          plugin_repositories_pinned: 3
          plugin_calendar: yes
          plugin_calendar_limit: 3
          repositories: 200
          repositories_batch: 300
          filename: github-metrics.svg
          committer_message: 'feat: Update User [skip ci]'
          optimize: yes
          experimental_features: --optimize-svg
          verify: yes
          # may or may not have stolen this from https://github.com/Exponential-Workload/Exponential-Workload/blob/main/.github/workflows/update.yml :troll:
